name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  # This job’s ID must match your required check name (“completed”)
  completed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run lint
        run: npm run lint
